# Generated by Django 6.1.1 on 2026-10-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customDB',
            fields=[
                ('name', models.CharField(max_length=12)),
                ('Mobile', models.IntegerField()),
                ('Address', models.TextField()),
                ('RC_Number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DL_Number', models.CharField(max_length=15)),
                ('Vehicle_Model', models.CharField(max_length=12)),
                ('Complaints', models.TextField()),
            ],
        ),
    ]
